# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-previous-config-job:
    runs-on: ubuntu-latest
    outputs:
        key: ${{ steps.get-key.outputs.key }}
    steps:
      - id: get-key
        run: |
             echo "key=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT

  # This workflow contains a single job called "build"
  build:
    needs: [my-previous-config-job]
    uses: ./.github/workflows/worker.yaml
    secrets:
      passphrase: ${{ needs.my-previous-config-job.outputs.key }}
