name: Worker workflow

on:
  workflow_call:
    secrets:
      passphrase:
        description: The input passphrase

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "secret: $(echo -n "${{secrets.passphrase}}" | sha256sum | cut -d' ' -f1)"

      - run: |
          exit 1
